#' Build CLaM R config
#'
#' @param param_list A named list of parameters
#' @param quietly Hide messages and warnings
#'
#' @return a named list of mass spec parameters
#'
#' @export
build_clamr_config <- function(param_list, quietly = FALSE) {
  stopifnot(all(class(param_list) == "list"))
  stopifnot(class(quietly) == "logical", length(quietly) == 1, quietly %in% c(TRUE, FALSE))

  if (any(names(param_list) == "") || class(names(param_list)) == "NULL") {
    stop("all entries of param_list must have names: some entries were not named")
  }

  # format and test mass accuracy specifications
  mass_tolerances <- format_mass_accuracy_tolerances(param_list, quietly)

  # parameters that have not been formatted
  misc_settings <- param_list[setdiff(names(param_list), names(mass_tolerances))]

  output_list <- append(mass_tolerances, misc_settings)
  class(output_list) <- c("clamr_config", class(output_list))

  output_list
}

#' Test CLaM R config
#'
#' @param clamr_config a named list of mass spec parameters with special formatting of instrument tolerances generated by \code{\link{build_clamr_config}}.
#'
#' @export
test_clamr_config <- function(clamr_config) {
  if (!("clamr_config" %in% class(clamr_config))) {
    stop("\"clamr_config\" was not constructed with \"build_clamr_config\"")
  }
}

#' Format mass accuracy tolerances
#'
#' @param acquisition_params a named list or named vector of parameters.
#' Parameters which match the regular exprssion "^MS[0-9]+tol" will be formatted.
#' Their values should be of the form "value unit". Valid units are amu and ppm.
#' @inheritParams build_clamr_config
#'
#' @return a list containing tolerances at a set of selection levels (1, 2, ...) and whether they are absolute or relative
#'
#' @examples
#' acquisition_params <- list(MS1tol = "10 ppm", MS2tol = "20ppm", other_par = "bar")
#' acquisition_params <- c(MS1tol = "10 ppm", MS2tol = "20ppm", other_par = "bar")
#'
#' @export
format_mass_accuracy_tolerances <- function(acquisition_params, quietly = FALSE) {
  if (!(all(class(acquisition_params) %in% c("character", "list")))) {
    stop("acquisition_params must either be a named list or named vector of parameters")
  }
  if (class(acquisition_params) == "list") {
    acquisition_params <- unlist(acquisition_params)
  }

  MSN_settings <- names(acquisition_params)[stringr::str_detect(names(acquisition_params), "^MS[0-9]+tol$")]
  if (length(MSN_settings) == 0 & !quietly) {
    warning("No mass tolerances were in acquisition_par_vector")
    return(list())
  } else {
    MSN_vector <- acquisition_params[MSN_settings]

    MSN_value_match <- stringr::str_detect(unname(MSN_vector), "^[0-9.]+[ ]*(amu|ppm)$")
    if (any(!MSN_value_match)) {
      stop(paste(paste(unname(MSN_vector[!MSN_value_match]), " is not a valid value for ", names(MSN_vector[!MSN_value_match]), sep = ""), collapse = "\n"))
    }

    MSN_values <- stringr::str_match(MSN_vector, "^([0-9.]+)[ ]*(amu|ppm)$")

    outputs <- list()
    for (i in seq_along(MSN_vector)) {
      if (quietly) {
        outputs[[names(MSN_vector)[i]]] <- suppressWarnings(format_mass_accuracy_input(as.numeric(MSN_values[i, 2]), MSN_values[i, 3]))
      } else {
        outputs[[names(MSN_vector)[i]]] <- format_mass_accuracy_input(as.numeric(MSN_values[i, 2]), MSN_values[i, 3])
      }
    }
    outputs
  }
}

#' Format Mass Accuracy Input
#'
#' @param mass_accuracy_tolerance mass accuracy of instrument in full scan data (MS1)
#' @param mass_accuracy_units amu or ppm
#'
#' @export
format_mass_accuracy_input <- function(mass_accuracy_tolerance, mass_accuracy_units) {
  stopifnot(class(mass_accuracy_tolerance) == "numeric", length(mass_accuracy_tolerance) == 1, mass_accuracy_tolerance > 0)
  stopifnot(class(mass_accuracy_units) == "character", length(mass_accuracy_units) == 1, mass_accuracy_units %in% c("amu", "ppm"))

  if (mass_accuracy_units == "ppm") {
    if (mass_accuracy_tolerance < 1) {
      warning("a ppm tolerance of ", mass_accuracy_tolerance, " may be too small")
    }
    tolerance <- list(
      tol = mass_accuracy_tolerance * 1e-6,
      absolute_or_relative = "relative"
    )
  } else if (mass_accuracy_units == "amu") {
    if (mass_accuracy_tolerance > 1) {
      warning("an amu tolerance of ", mass_accuracy_tolerance, " may be too large")
    }
    tolerance <- list(
      tol = mass_accuracy_tolerance,
      absolute_or_relative = "absolute"
    )
  }
  tolerance
}

#' CLaM R require tolerances
#'
#' Require a set of tolerance parameters and verify that they are appropriately formatted.
#'
#' @inheritParams test_clamr_config
#' @param required_msLevels an integer vector of required msLevel tolerances
#'
#' @return returns 0 invisibly
#'
#' @export
require_tolerances <- function(clamr_config, required_msLevels) {
  test_clamr_config(clamr_config)
  stopifnot("integer" %in% class(required_msLevels))

  required_tol_parameters <- paste0("MS", required_msLevels, "tol")
  missing_required_tol_parameters <- setdiff(required_tol_parameters, names(clamr_config))
  if (length(missing_required_tol_parameters) != 0) {
    stop(paste(missing_required_tol_parameters, collapse = " & "), " are required tolerances; provide these when calling build_clamr_config")
  }
  check_tolerances(clamr_config)

  invisible(0)
}

check_tolerances <- function(clamr_config) {
  tolerance_parameters <- stringr::str_extract(names(clamr_config), "^MS[0-9]+tol$")
  tolerance_parameters <- tolerance_parameters[!is.na(tolerance_parameters)]

  if (length(tolerance_parameters) != length(unique(tolerance_parameters))) {
    stop("tolerance parameters duplicated in clamr_config")
  }

  for (a_tol_par in tolerance_parameters) {
    a_tol_par_value <- clamr_config[[a_tol_par]]

    if (!"list" %in% class(a_tol_par_value)) {
      stop(a_tol_par, " is misformatted (it should be a list): set tolerances with build_clamr_config")
    }
    if (!all(c("tol", "absolute_or_relative") %in% names(a_tol_par_value))) {
      stop(a_tol_par, " is misformatted (it did not contain a tol & absolute_or_relative value): set tolerances with build_clamr_config")
    }
    if (!"numeric" %in% class(a_tol_par_value$tol) || a_tol_par_value$tol <= 0) {
      stop(a_tol_par, " is misformatted (tol was not a non-negative numeric): set tolerances with build_clamr_config")
    }
    if (!"character" %in% class(a_tol_par_value$absolute_or_relative) || length(a_tol_par_value$absolute_or_relative) != 1 || !a_tol_par_value$absolute_or_relative %in% c("absolute", "relative")) {
      stop(a_tol_par, " is misformatted (absolute_or_relative should be either \"absolute\" or \"relative\"): set tolerances with build_clamr_config")
    }
  }
  invisible(0)
}

#' CLaM R Config Assign
#'
#' Write each entry of the config to objects (for debugging)
#'
#' @inheritParams test_clamr_config
clamr_config_assign <- function(clamr_config) {
  test_clamr_config(clamr_config)

  purrr::walk2(names(clamr_config), unname(clamr_config), assign, envir = .GlobalEnv)
}
