#' Get all valid file extensions
#'
#' All valid file extensions should be stored here, and not anywhere else.
#'
#' Anything that needs a valid file extension should call into this function.
#'
#' @export
get_valid_ms_file_extensions <- function() {
  c(".mzXML", ".mzXML.gz", ".mzML", ".mzML.gz", ".netCDF", ".netCDF.gz", ".mzData", ".mzData.gz")
}

#' Strip file extension
#'
#' Iterate through all valid file extensions, and remove them.
#' If no valid extension is found, throw an error.
#'
#' This function is public, disallowing overwriting of valid file_extensions.
#'
#' @param file_names list of file names. can be a mixture of types (mzML, mzXML, etc)
#'
#' @return the ms file name without extension.
#'
#' @export
strip_ms_file_extension <- function(file_names) {
  file_extensions <- get_valid_ms_file_extensions()
  return(strip_ms_file_extension_from_extensions(file_names, file_extensions))
}

#' package-local function that does the actual work of modifying file extensions.
#'
#' @inheritParams strip_ms_file_extension
#' @param file_extensions a character vector of extensions as generated by \link{get_valid_ms_file_extensions}.
#'
#' @return file with file extension stripped off.
#'
#' @export
strip_ms_file_extension_from_extensions <- function(file_names, file_extensions) {
  file_names_no_exts <- file_names

  for (i in 1:length(file_names)) {
    found_ext <- FALSE
    file_name <- file_names[i]

    for (extension in file_extensions) {
      if (endsWith(file_name, extension)) {
        file_names_no_exts[i] <- sub(paste(extension, "$", sep = ""), "", file_name)
        found_ext <- TRUE
        break
      }
    }

    if (!found_ext) {
      stop(paste("file '", file_name, "' does not end with a valid ms file extension.  If the extension is valid, please add it to clamdb<ms_file_import.R>::valid_ms_file_extensions", sep = ""))
    }
  }

  return(file_names_no_exts)
}
